name: Image Shepherd Update Cron
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 1,15 * * # Approximation of 2 weeks at 3:00AM EST

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23'
      - name: Create clouds.yaml from secret
        run: |
          echo "${{ secrets.CLOUDS_YAML }}" > clouds.yaml
          chmod 600 clouds.yaml
      - name: Run image-shephard
        run: go run cmd/image-shepherd/shepherd.go
