name: Image Shepherd Update Cron
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 1,15 * * # Approximation of 2 weeks at 3:00AM EST

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Create clouds.yaml from secret
        run: |
          echo "${{ secrets.CLOUDS_YAML }}" > clouds.yaml
          chmod 600 clouds.yaml
      - name: Run Docker
        run: docker run -v $PWD/clouds.yaml:/opt/image-shepherd/clouds.yaml -v $PWD/images.yaml:/opt/image-shepherd/images.yaml ghcr.io/hackucf/image-shepherd
